Repository clustermod/HCMF3-Loadouts, pull requests merged in 2024-02, with the labels that each got.

#35 Logistics File - Add custom file contents
  loadouts/ukraine/loadouts/README.md
Labels: kind/enhancement

#36 General - Add German motorized infantry loadout and logistics file
  loadouts/germany/loadouts/README.md
  loadouts/germany/loadouts/deu_2024_jäger_flecktarn_v5.sqf
  loadouts/germany/logistics/README.md
  loadouts/germany/logistics/deu_2024_jäger_logistics_flecktarn_v5.sqf
Labels: kind/enhancement, status/review pending, area/documentation

#37 General - add German loadout documentation
  loadouts/germany/loadouts/README.md
  loadouts/germany/loadouts/deu_2012_ksk_tropentarn.sqf
  loadouts/germany/loadouts/deu_2015_psa_bpo_solid-urban.sqf
  loadouts/germany/loadouts/deu_2023_fallschirmjäger_flecktarn.sqf
  loadouts/germany/loadouts/deu_2023_ksk_multitarn_v4.sqf
  loadouts/germany/loadouts/deu_2023_pzgren_flecktarn_v5.sqf
  loadouts/germany/loadouts/deu_2023_pzgren_tropentarn_v5.sqf
  loadouts/germany/loadouts/deu_ca2010_fallschirmjaeger_flecktarn.sqf
Labels: status/pending, area/documentation

#38 Documentation - Add all missing README entries
  loadouts/germany/loadouts/README.md
  loadouts/germany/logistics/README.md
  loadouts/germany/logistics/deu_bundeswehr_logistics_template.sqf
  loadouts/norway/loadouts/README.md
  loadouts/poland/loadouts/README.md
  loadouts/russia/ai/README.md
  loadouts/russia/loadouts/README.md
  loadouts/ukraine/loadouts/README.md
  loadouts/unaffiliated/loadouts/README.md
  loadouts/unaffiliated/loadouts/irg_2010s_pmc3_greenlizard.sqf
  loadouts/unaffiliated/loadouts/irg_2010s_pmc3_tigerstripe.sqf
  loadouts/unaffiliated/loadouts/irg_2010s_pmc3_woodland.sqf
  loadouts/united_states/loadouts/README.md
  loadouts/united_states/loadouts/usa_1968_macv-sog_spray.sqf
  loadouts/united_states/loadouts/usa_1989_us-rangers_woodland.sqf
  loadouts/united_states/loadouts/usa_2004_delta-force_woodland.sqf
  loadouts/united_states/loadouts/usa_2012_pararescue-jumpers_full-heli-crew-multicam.sqf
  loadouts/united_states/loadouts/usa_2018_75th-ranger-regiment_multicam.sqf
  loadouts/united_states/loadouts/usa_ca2020_marsoc_m81.sqf
  loadouts/united_states/loadouts/usa_na_modern-marsoc_m81.sqf
Labels: kind/enhancement, status/review pending, area/documentation

#40 General - Improve README with a "request loadout" button
  README.md
Labels: kind/enhancement
