Repository clustermod/HCMF3-Loadouts, pull requests merged in 2024-01, with the labels that each got.

#26 General - Add contributing guidelines and update README
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  AUTHORS.txt
  LICENSE
  README.md
  extra/assets/logo/black/cmf3_logo.png
  extra/assets/logo/black/cmf3_logo.xcf
  extra/assets/logo/black/cmf3_logo_trans.png
  extra/assets/logo/white/cmf3_logo.png
  extra/assets/logo/white/cmf3_logo.xcf
  extra/assets/logo/white/cmf3_logo_trans.png
Labels: kind/enhancement, kind/task, status/review pending, area/documentation

#29 General - Improve and update full mission sets folder and files
  Full Mission Sets/V5_GER_2023_Panzertruppe_Flecktarn_Set/V5_GER_2023_Panzertruppe_Loadout_Flecktarn.sqf
  Full Mission Sets/V5_GER_2023_PzGren_Flecktarn_Set/V5_GER_2023_PzGrenIdZ_Garage_Flecktarn.sqf
  full_mission_sets/congo_1998_katanga_belgian_full_mission_set_v5/katanga_1961_logistics_v5.sqf
  full_mission_sets/congo_1998_katanga_belgian_full_mission_set_v5/katanga_1961_v5.sqf
  full_mission_sets/deu_2023_fschjg_flecktarn_full_mission_set_v5/deu_2023_fallschirmjäger_garage_flecktarn_v5.sqf
  full_mission_sets/deu_2023_fschjg_flecktarn_full_mission_set_v5/deu_2023_fallschirmjäger_loadout_flecktarn_v5.sqf
  full_mission_sets/deu_2023_fschjg_flecktarn_full_mission_set_v5/deu_2023_fallschirmjäger_logistics_flecktarn._v5.sqf
  full_mission_sets/deu_2023_panzertruppe_flecktarn_full_mission_set_v5/deu_2023_panzertruppe_Garage_flecktarn_v5.sqf
  full_mission_sets/deu_2023_panzertruppe_flecktarn_full_mission_set_v5/deu_2023_panzertruppe_Loadout_flecktarn_v5.sqf
  full_mission_sets/deu_2023_panzertruppe_flecktarn_full_mission_set_v5/deu_2023_panzertruppe_Logistics_flecktarn_v5.sqf
  full_mission_sets/deu_2023_panzertruppe_flecktarn_full_mission_set_v5/deu_2023_panzertruppe_WARNO_Template.sqf
  full_mission_sets/deu_2023_pzgren_flecktarn_full_mission_set_v5/deu_2023_pzgren_garage_flecktarn_v5.sqf
  full_mission_sets/deu_2023_pzgren_flecktarn_full_mission_set_v5/deu_2023_pzgren_loadout_flecktarn_v5.sqf
  full_mission_sets/deu_2023_pzgren_flecktarn_full_mission_set_v5/deu_2023_pzgren_logistics_flecktarn_v5.sqf
  full_mission_sets/rus_1998_vdv_full_mission_set_v5/russia_vdv_1998_logistics_v5.sqf
  full_mission_sets/rus_1998_vdv_full_mission_set_v5/russia_vdv_1998_v5.sqf
Labels: area/compatibility, area/config, kind/enhancement

#31 Loadouts - Add 2005 U.S. Delta Forces in 3CD
  loadouts/united_states/loadouts/README.md
  loadouts/united_states/loadouts/usa_2005_delta_3cd.sqf
  loadouts/united_states/logistics/README.md
  loadouts/united_states/logistics/usa_2005_delta_logistics.sqf
Labels: kind/loadout request

#32 Loadouts - Fix Documentation: Bad Link
  loadouts/united_states/loadouts/README.md
Labels: kind/bug fix
